-- Phân công QC theo từng (lô hàng × sản phẩm) — bảng "Chọn lô để kiểm" ở
-- tab Đánh giá chất lượng giờ tách mỗi dòng là 1 sản phẩm (kiểm QC làm
-- theo từng sản phẩm). Mỗi dòng cho phép nhập tay 2 thứ ngay trong bảng:
--   - inspection_date : "Ngày kiểm hàng" (nhập tay, không tự suy ra)
--   - qc_inspector    : tên người QC phụ trách — mở khối nhập kết quả cho
--                       đúng lô-sản phẩm đó sẽ tự điền sẵn ô "Người kiểm".
--
-- Không ảnh hưởng qc_checks (kết quả kiểm thực tế vẫn ghi ở đó). Bảng này
-- chỉ là lớp phân công / ghi chú lịch kiểm.
--
-- Cách dùng: Supabase Dashboard → SQL Editor → dán cả file → Run.
-- An toàn chạy nhiều lần.

create table if not exists public.qc_assignments (
  id bigint generated by default as identity primary key,
  batch_code text not null,
  san_pham text not null default '',
  inspection_date date,
  qc_inspector text,
  created_at timestamptz default now()
);

-- 1 dòng cho mỗi (lô, sản phẩm) — sản phẩm rỗng ('') = lô chưa tách sản phẩm.
create unique index if not exists qc_assignments_batch_sanpham_key
  on public.qc_assignments (batch_code, san_pham);

alter table public.qc_assignments enable row level security;

-- Cùng mô hình phân quyền với qc_checks / batch_trace_products:
-- đọc = mọi tài khoản đã đăng nhập, ghi = admin hoặc role qc.
do $$
declare
  pol record;
begin
  for pol in (select policyname from pg_policies where schemaname = 'public' and tablename = 'qc_assignments') loop
    execute format('drop policy if exists %I on public.qc_assignments', pol.policyname);
  end loop;
  execute 'create policy "role_select" on public.qc_assignments for select using (auth.role() = ''authenticated'')';
  execute 'create policy "role_insert" on public.qc_assignments for insert with check (public.current_role() in (''admin'', ''qc''))';
  execute 'create policy "role_update" on public.qc_assignments for update using (public.current_role() in (''admin'', ''qc'')) with check (public.current_role() in (''admin'', ''qc''))';
  execute 'create policy "role_delete" on public.qc_assignments for delete using (public.current_role() in (''admin'', ''qc''))';
end $$;

-- Ghi audit log nếu đã có hàm log_audit_event (2026-08-25_audit_log.sql) — bỏ qua an toàn nếu chưa.
do $$
begin
  if exists (select 1 from pg_proc where proname = 'log_audit_event') then
    drop trigger if exists trg_audit_log on public.qc_assignments;
    create trigger trg_audit_log after insert or update or delete on public.qc_assignments
      for each row execute function public.log_audit_event();
  end if;
end $$;
