-- Đơn hàng nhiều sản phẩm — thay ô "Sản phẩm" + "Số lượng dự kiến" gộp
-- chung 1 dòng cũ (batch_info.san_pham/so_luong_du_kien) bằng danh sách
-- nhiều dòng, mỗi dòng 1 sản phẩm kèm số lượng dự kiến riêng.
--
-- Không xóa 2 cột cũ trên batch_info — đơn tạo trước khi có bảng này vẫn
-- đọc được qua đó (xem orderHintText trong app.js, tự rơi về cột cũ nếu lô
-- chưa có dòng nào trong bảng mới).
--
-- Cách dùng: dán vào Supabase Dashboard -> SQL Editor -> Run (chạy 1 lần).
-- An toàn chạy nhiều lần.

create table if not exists public.batch_info_products (
  id bigint generated by default as identity primary key,
  batch text not null,
  san_pham text not null,
  so_luong_du_kien text,
  created_at timestamptz default now()
);
alter table public.batch_info_products enable row level security;

-- Cùng nhóm quyền với batch_info (bảng gốc mà nó mở rộng ra) — xem
-- supabase/2026-07-21_auth_roles.sql, tables_qc: đọc = mọi người đã đăng
-- nhập, ghi (thêm/sửa/xóa) = admin hoặc role qc.
do $$
declare
  pol record;
begin
  for pol in (select policyname from pg_policies where schemaname = 'public' and tablename = 'batch_info_products') loop
    execute format('drop policy if exists %I on public.batch_info_products', pol.policyname);
  end loop;
  execute 'create policy "role_select" on public.batch_info_products for select using (auth.role() = ''authenticated'')';
  execute 'create policy "role_insert" on public.batch_info_products for insert with check (public.current_role() in (''admin'', ''qc''))';
  execute 'create policy "role_update" on public.batch_info_products for update using (public.current_role() in (''admin'', ''qc'')) with check (public.current_role() in (''admin'', ''qc''))';
  execute 'create policy "role_delete" on public.batch_info_products for delete using (public.current_role() in (''admin'', ''qc''))';
end $$;
