-- Module "Thu mua & Bán chợ" — thu mua dừa trực tiếp, sơ chế, bán ra thị
-- trường nội địa (bán chợ). Module này ĐỘC LẬP hoàn toàn với chuỗi cung ứng
-- xuất khẩu hiện có — không đụng tới raw_batches/purchase_orders/
-- factory_batches/qc_checks... của các module khác.
--
-- Cách dùng: mở Supabase Dashboard → SQL Editor → dán toàn bộ file này → Run.
-- An toàn chạy nhiều lần (dùng IF NOT EXISTS).

-- ============ Thu mua ============
create table if not exists public.market_purchases (
  id bigint generated by default as identity primary key,
  ngay_mua date,
  nguon_mua text not null,          -- tên thương lái/vườn (nhập tay, không liên kết NCC)
  so_luong_trai numeric,
  don_gia_mua numeric,              -- đơn giá mua (đ/trái)
  ghi_chu text,
  created_at timestamptz default now(),
  deleted_at timestamptz
);
alter table public.market_purchases enable row level security;
drop policy if exists "Public full access" on public.market_purchases;
create policy "Public full access" on public.market_purchases for all using (true) with check (true);

-- ============ Sơ chế ============
create table if not exists public.market_processing (
  id bigint generated by default as identity primary key,
  ngay_so_che date,
  ghi_chu text,
  created_at timestamptz default now(),
  deleted_at timestamptz
);
alter table public.market_processing enable row level security;
drop policy if exists "Public full access" on public.market_processing;
create policy "Public full access" on public.market_processing for all using (true) with check (true);

-- Nguồn nguyên liệu cho 1 lần sơ chế — có thể gộp trái từ nhiều lô thu mua
-- khác nhau (VD: 1 lần sơ chế dùng trái từ 2 lần thu mua trước đó).
create table if not exists public.market_processing_sources (
  id bigint generated by default as identity primary key,
  processing_id bigint not null references public.market_processing(id) on delete cascade,
  purchase_id bigint not null references public.market_purchases(id),
  so_trai_su_dung numeric not null,
  created_at timestamptz default now()
);
alter table public.market_processing_sources enable row level security;
drop policy if exists "Public full access" on public.market_processing_sources;
create policy "Public full access" on public.market_processing_sources for all using (true) with check (true);

-- Sản phẩm đầu ra của 1 lần sơ chế — 1 lần có thể ra nhiều loại sản phẩm
-- (VD: dừa gọt vỏ loại 1 + loại 2), tất cả vẫn tính theo đơn vị trái.
create table if not exists public.market_processing_outputs (
  id bigint generated by default as identity primary key,
  processing_id bigint not null references public.market_processing(id) on delete cascade,
  ten_san_pham text not null,
  so_luong_trai numeric not null,
  created_at timestamptz default now()
);
alter table public.market_processing_outputs enable row level security;
drop policy if exists "Public full access" on public.market_processing_outputs;
create policy "Public full access" on public.market_processing_outputs for all using (true) with check (true);

-- ============ Bán chợ ============
create table if not exists public.market_sales (
  id bigint generated by default as identity primary key,
  ngay_ban date,
  khach_hang text,                  -- tên khách/chợ (nhập tay)
  ten_san_pham text not null,       -- khớp tên với market_processing_outputs.ten_san_pham
  so_luong_trai numeric,
  don_gia_ban numeric,              -- đơn giá bán (đ/trái)
  ghi_chu text,
  created_at timestamptz default now(),
  deleted_at timestamptz
);
alter table public.market_sales enable row level security;
drop policy if exists "Public full access" on public.market_sales;
create policy "Public full access" on public.market_sales for all using (true) with check (true);
