-- Tách "hao hụt" ở Xưởng Ba Phi thành 2 loại rõ ràng, thay vì gộp chung 1
-- số như trước (Nhập − Thành phẩm):
--   - "Rớt/chưa đạt chuẩn" — vẫn tính tự động (Nhập − Thành phẩm − Dạt bỏ),
--     là phần CÓ THỂ còn cứu được (bán chợ/gán bù qua "Xử lý hàng tồn & rớt"
--     ở tab Tồn kho — không đổi gì ở đó).
--   - "Dạt bỏ" (bảng mới) — nhập tay ngay lúc "Cập nhật sản xuất", biết chắc
--     là hư hỏng vật lý (bể gáo, nứt đầu...) không dùng được nữa, không cần
--     đưa qua bước xử lý ở Tồn kho nữa.
--
-- "Hao hụt %" ở KPI đầu trang ("Hao hụt gọt vỏ trung bình") và ở bảng chi
-- tiết giờ tính theo Dạt bỏ ÷ Số lượng nhập (theo yêu cầu) — không còn gộp
-- chung với phần Rớt/chưa đạt chuẩn.
--
-- Cách dùng: mở Supabase Dashboard → SQL Editor → dán toàn bộ file này → Run.
-- An toàn chạy nhiều lần.

create table if not exists public.factory_batch_waste (
  id bigint generated by default as identity primary key,
  factory_batch_id bigint not null references public.factory_batches(id) on delete cascade,
  ly_do text not null,
  ly_do_ghi_chu text,
  so_luong numeric not null,
  created_at timestamptz default now()
);

do $$
begin
  alter table public.factory_batch_waste
    add constraint factory_batch_waste_ly_do_check
    check (ly_do in ('Bể gáo', 'Nứt đầu', 'Khác'));
exception when duplicate_object then null;
end $$;

alter table public.factory_batch_waste enable row level security;

-- Cùng nhóm quyền với factory_batch_boxes (module Xưởng Ba Phi).
do $$
declare
  pol record;
begin
  for pol in (select policyname from pg_policies where schemaname = 'public' and tablename = 'factory_batch_waste') loop
    execute format('drop policy if exists %I on public.factory_batch_waste', pol.policyname);
  end loop;
  execute 'create policy "role_select" on public.factory_batch_waste for select using (auth.role() = ''authenticated'')';
  execute 'create policy "role_insert" on public.factory_batch_waste for insert with check (public.can_write(''xuong_ba_phi''))';
  execute 'create policy "role_update" on public.factory_batch_waste for update using (public.can_write(''xuong_ba_phi'')) with check (public.can_write(''xuong_ba_phi''))';
  execute 'create policy "role_delete" on public.factory_batch_waste for delete using (public.can_write(''xuong_ba_phi''))';
end $$;

-- Ghi audit log cho bảng mới — cần hàm public.log_audit_event() đã tạo ở
-- 2026-08-25_audit_log.sql (bỏ qua an toàn nếu chưa chạy file đó).
do $$
begin
  if exists (select 1 from pg_proc where proname = 'log_audit_event') then
    drop trigger if exists trg_audit_log on public.factory_batch_waste;
    create trigger trg_audit_log after insert or update or delete on public.factory_batch_waste
      for each row execute function public.log_audit_event();
  end if;
end $$;
