-- Cho phép 1 đợt sản xuất khai báo NHIỀU Quy cách (biết được sau khi đóng
-- gói xong, không phải lúc nhập nguyên liệu) — VD: cùng 1 lô Dừa trọc
-- nhưng đóng 60 thùng loại 25 trái/thùng + 40 thùng loại 12 trái/thùng.
-- Thay cho cột factory_batches.quy_cach (1 giá trị/đợt) — cột cũ vẫn giữ
-- lại trong DB (không xoá, tránh mất dữ liệu cũ) nhưng app không dùng nữa,
-- toàn bộ tính toán Số lượng thùng giờ cộng dồn từ bảng này.
--
-- Cách dùng: Supabase Dashboard → SQL Editor → dán toàn bộ file → Run.
-- An toàn chạy nhiều lần.

create table if not exists public.factory_batch_boxes (
  id bigint generated by default as identity primary key,
  factory_batch_id bigint not null references public.factory_batches(id) on delete cascade,
  quy_cach numeric not null,
  so_luong_thung numeric not null,
  created_at timestamptz default now()
);
alter table public.factory_batch_boxes enable row level security;

drop policy if exists "role_select" on public.factory_batch_boxes;
drop policy if exists "role_insert" on public.factory_batch_boxes;
drop policy if exists "role_update" on public.factory_batch_boxes;
drop policy if exists "role_delete" on public.factory_batch_boxes;
drop policy if exists "Public full access" on public.factory_batch_boxes;

-- Cùng quyền module "xuong_ba_phi" như factory_batches (xem
-- 2026-07-22_dynamic_permissions.sql) — select mở cho user đã đăng nhập,
-- ghi/sửa/xoá theo can_write('xuong_ba_phi').
create policy "role_select" on public.factory_batch_boxes for select using (auth.role() = 'authenticated');
create policy "role_insert" on public.factory_batch_boxes for insert with check (public.can_write('xuong_ba_phi'));
create policy "role_update" on public.factory_batch_boxes for update using (public.can_write('xuong_ba_phi')) with check (public.can_write('xuong_ba_phi'));
create policy "role_delete" on public.factory_batch_boxes for delete using (public.can_write('xuong_ba_phi'));
