-- "Xử lý hàng tồn & rớt" ở tab Tồn kho (Xưởng Ba Phi) — gộp chung 2 nguồn
-- cần xử lý vào 1 luồng duy nhất:
--   'dat'     Hàng dạt ra lúc sản xuất, CHƯA đóng gói (= raw_batches.soluong
--             − factory_batches.finished_qty, tính tự động, không nhập tay).
--   'ton_du'  Thành phẩm ĐÃ đóng gói nhưng còn dư, chưa xuất hết (chính là
--             cột "Tồn kho (trái)" ở tab Xuất hàng — quy_cach × (đã đóng gói
--             − đã xuất) của từng Sản phẩm+Quy cách).
--
-- Cả 2 nguồn xử lý theo 2 hướng như nhau:
--   'market'   Bán chợ — 'dat' thì trừ thẳng khỏi dạt tồn kho của lô gốc;
--              'ton_du' thì cộng thẳng vào "Đã xuất" của CHÍNH lô gốc (rời
--              kho qua đường bán chợ thay vì xuất khách).
--   'reassign' Sản xuất qua đơn khác — gán bù vào "Đã xuất" (thùng) của 1 lô
--              hàng khác (target_batch/san_pham/quy_cach); với 'ton_du' thì
--              đồng thời cũng cộng vào "Đã xuất" của lô gốc (hàng rời kho gốc,
--              tính vào sản lượng xuất của lô đích).
--
-- Cách dùng: Supabase Dashboard → SQL Editor → dán toàn bộ file → Run.
-- An toàn chạy nhiều lần.

create table if not exists public.factory_culled_processing (
  id bigint generated by default as identity primary key,
  source_type text not null,         -- 'dat' | 'ton_du'
  raw_batch_id bigint references public.raw_batches(id),   -- chỉ 'dat'
  source_batch text,                 -- chỉ 'ton_du'
  source_chung_loai text,
  source_san_pham text,
  source_quy_cach numeric,
  xu_ly_type text not null,          -- 'market' | 'reassign'
  processed_date date,
  qty_trai numeric not null,         -- số trái đã xử lý (trừ khỏi "Còn lại" của nguồn)
  so_luong_thung numeric,            -- chỉ 'ton_du': số thùng tương ứng, cộng vào "Đã xuất" của lô gốc
  target_batch text,                 -- lô hàng đích (chỉ 'reassign')
  target_chung_loai text,            -- chủng loại của lô đích khớp đúng Sản phẩm+Quy cách (tự dò khi lưu)
  target_san_pham text,
  target_quy_cach numeric,
  target_so_luong_thung numeric,     -- số thùng gán bù vào "Đã xuất" của lô đích
  note text,
  created_at timestamptz default now(),
  deleted_at timestamptz
);
alter table public.factory_culled_processing enable row level security;

-- Cùng mô hình phân quyền với các bảng khác của Xưởng Ba Phi (raw_batches,
-- factory_batches, factory_finished_stock, factory_staff — xem
-- supabase/2026-07-21_auth_roles.sql): đọc = mọi người đã đăng nhập, ghi
-- (thêm/sửa/xóa) = admin hoặc role san_xuat.
do $$
declare
  pol record;
begin
  for pol in (select policyname from pg_policies where schemaname = 'public' and tablename = 'factory_culled_processing') loop
    execute format('drop policy if exists %I on public.factory_culled_processing', pol.policyname);
  end loop;
  execute 'create policy "role_select" on public.factory_culled_processing for select using (auth.role() = ''authenticated'')';
  execute 'create policy "role_insert" on public.factory_culled_processing for insert with check (public.current_role() in (''admin'', ''san_xuat''))';
  execute 'create policy "role_update" on public.factory_culled_processing for update using (public.current_role() in (''admin'', ''san_xuat'')) with check (public.current_role() in (''admin'', ''san_xuat''))';
  execute 'create policy "role_delete" on public.factory_culled_processing for delete using (public.current_role() in (''admin'', ''san_xuat''))';
end $$;
