-- Lịch sử hoạt động (audit log) — trước đây hệ thống không có cách nào biết
-- AI đã thêm/sửa/xóa dữ liệu, chỉ Thùng rác cho biết CÁI GÌ bị xóa và LÚC
-- NÀO (không biết ai). File này thêm 1 bảng ghi log tự động qua trigger trên
-- các bảng nghiệp vụ chính — không có đường ghi nào từ client, chỉ đọc qua
-- UI (Tab Quản lý tài khoản → Lịch sử hoạt động, chỉ Admin xem được).
--
-- Cách dùng: mở Supabase Dashboard → SQL Editor → dán toàn bộ file này → Run.
-- An toàn chạy nhiều lần.

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid,
  actor_email text,
  actor_role text,
  action text not null check (action in ('insert', 'update', 'delete')),
  table_name text not null,
  record_id text,
  batch_code text,
  old_data jsonb,
  new_data jsonb
);
alter table public.audit_log enable row level security;

-- Chỉ Admin đọc được (đúng nơi hiển thị — Tab Quản lý tài khoản chỉ Admin
-- vào được). Không có policy insert/update/delete nào cho role thường — chỉ
-- trigger SECURITY DEFINER bên dưới mới ghi được vào bảng này.
drop policy if exists "role_select" on public.audit_log;
create policy "role_select" on public.audit_log
  for select using (public.current_role() = 'admin');

create index if not exists audit_log_created_at_idx on public.audit_log (created_at desc);
create index if not exists audit_log_table_name_idx on public.audit_log (table_name);
create index if not exists audit_log_batch_code_idx on public.audit_log (batch_code);

-- security definer để ghi được vào audit_log dù role đang thao tác (VD: qc,
-- ncc...) không có quyền insert trực tiếp vào bảng này — cùng kỹ thuật với
-- current_role()/can_write() (xem 2026-07-21_auth_roles.sql).
create or replace function public.log_audit_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_email text;
  v_actor_role text;
  v_old jsonb;
  v_new jsonb;
  v_record_id text;
  v_batch_code text;
begin
  select email, role into v_actor_email, v_actor_role from public.profiles where id = v_actor_id;

  if TG_OP = 'DELETE' then
    v_old := to_jsonb(OLD);
  else
    v_new := to_jsonb(NEW);
    if TG_OP = 'UPDATE' then
      v_old := to_jsonb(OLD);
    end if;
  end if;

  v_record_id := coalesce(v_new ->> 'id', v_old ->> 'id');
  v_batch_code := coalesce(v_new ->> 'batch_code', v_new ->> 'batch', v_old ->> 'batch_code', v_old ->> 'batch');

  insert into public.audit_log (actor_id, actor_email, actor_role, action, table_name, record_id, batch_code, old_data, new_data)
  values (v_actor_id, v_actor_email, v_actor_role, lower(TG_OP), TG_TABLE_NAME, v_record_id, v_batch_code, v_old, v_new);

  return coalesce(NEW, OLD);
end;
$$;

-- Gắn trigger cho các bảng nghiệp vụ chính — không audit chính bảng
-- audit_log, và không audit module_permissions/profiles theo cách khác biệt
-- (vẫn ghi log bình thường, chỉ là 2 bảng này đặc biệt nhạy cảm nên nằm
-- trong danh sách để đảm bảo có log đổi vai trò/quyền).
do $$
declare
  t text;
  tables_to_audit text[] := array[
    'raw_batches', 'raw_suppliers', 'suppliers', 'purchase_orders',
    'factory_batches', 'factory_batch_boxes', 'factory_finished_stock',
    'factory_staff', 'factory_culled_processing', 'shelf_life_reference',
    'qc_checks', 'shipments', 'documents_checklist', 'feedbacks',
    'batch_info', 'batch_info_products', 'batch_trace_products',
    'market_purchases', 'market_processing', 'market_processing_sources',
    'market_processing_outputs', 'market_sales',
    'profiles', 'module_permissions'
  ];
begin
  foreach t in array tables_to_audit loop
    if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = t) then
      execute format('drop trigger if exists trg_audit_log on public.%I', t);
      execute format('create trigger trg_audit_log after insert or update or delete on public.%I for each row execute function public.log_audit_event()', t);
    end if;
  end loop;
end $$;
