-- Ghi nhận đóng cont — dữ liệu QC nhập lúc đóng hàng thực tế (bao bì, chất
-- lượng, số lượng thực tế, tình trạng container, sơ đồ load hàng, ảnh) để tự
-- điền đầy đủ vào báo cáo Word khi xuất, thay vì QC phải tự gõ tay toàn bộ
-- vào file Word như trước. 1 dòng/lô hàng, upsert theo batch.
--
-- Cách dùng: dán vào Supabase Dashboard -> SQL Editor -> Run (chạy 1 lần).
-- An toàn chạy nhiều lần.

create table if not exists public.qc_closing_records (
  id bigint generated by default as identity primary key,
  batch text not null,
  -- Mảng tối đa 3 dòng: {loai_thung, kich_thuoc, trong_luong, mau_sac, so_lop, tinh_trang_truoc, tinh_trang_sau, ghi_chu}
  bao_bi jsonb,
  -- Object khoá theo tên loại hàng: {"<loại hàng>": {trong_luong, ngoai_quan, tieu_chi_khac}}
  chat_luong jsonb,
  -- Object khoá theo tên loại hàng: {"<loại hàng>": "<số lượng thực tế>"}, cộng thêm key "_tong"
  so_luong_thuc_te jsonb,
  -- Object khoá theo tên chỉ tiêu cố định (Hệ thống làm lạnh...): {"<chỉ tiêu>": {tinh_trang, quyet_dinh, ghi_chu}}
  container_check jsonb,
  -- Mảng động: [{lop, loai_hang, so_luong}, ...]
  so_do_load_hang jsonb,
  -- Mảng đường dẫn ảnh trong Storage bucket "qc-photos", tối đa 9
  photo_paths jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);
alter table public.qc_closing_records enable row level security;
drop policy if exists "Public full access" on public.qc_closing_records;
create policy "Public full access" on public.qc_closing_records for all using (true) with check (true);

do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'qc_closing_records'
      and constraint_name = 'qc_closing_records_batch_key'
  ) then
    alter table public.qc_closing_records add constraint qc_closing_records_batch_key unique (batch);
  end if;
end $$;

-- Storage bucket chứa ảnh load hàng (Mục 6) — public đọc (ảnh không nhạy
-- cảm, cần đọc thẳng URL để nhúng vào file Word lúc xuất báo cáo).
insert into storage.buckets (id, name, public)
values ('qc-photos', 'qc-photos', true)
on conflict (id) do nothing;

drop policy if exists "qc-photos public read" on storage.objects;
create policy "qc-photos public read" on storage.objects for select
  using (bucket_id = 'qc-photos');

drop policy if exists "qc-photos public write" on storage.objects;
create policy "qc-photos public write" on storage.objects for insert
  with check (bucket_id = 'qc-photos');

drop policy if exists "qc-photos public delete" on storage.objects;
create policy "qc-photos public delete" on storage.objects for delete
  using (bucket_id = 'qc-photos');
