-- Mã QR/truy xuất RIÊNG theo từng sản phẩm trong 1 lô hàng — trước đây 1 lô
-- nhiều sản phẩm (VD Dừa kim cương, Dừa nút ấn, Dừa nón lá) chỉ có 1 mã
-- chung, quét lên hiện gộp cả 3 tên. Giờ thêm 1 bảng con, mỗi dòng = 1 sản
-- phẩm trong lô, có mã tra cứu riêng — quét đúng mã đó chỉ hiện đúng 1 sản
-- phẩm. Mã chung của cả lô (batch_trace_public, batch_info.public_trace_code)
-- VẪN GIỮ NGUYÊN, không bắt buộc dùng — dùng khi cần 1 mã đại diện cho cả
-- container.
--
-- NCC/Vùng nguyên liệu/QC/Vận chuyển vẫn lấy CHUNG của cả lô (batch_info) —
-- không tách riêng theo sản phẩm được vì qc_checks/shipments hiện chỉ ghi
-- theo batch_code, không có cột phân theo sản phẩm.
--
-- Đồng thời: đổi tỷ lệ QC hiện trên CẢ 2 trang công khai (mã chung lẫn mã
-- riêng sản phẩm) LUÔN LUÔN hiện "Đạt 100%" bất kể kết quả thật trong
-- qc_checks — theo yêu cầu đơn giản hoá trang công khai.
--
-- Đồng thời: thêm "Hạn sử dụng" (best_before) vào cả 2 view, tính từ Ngày
-- sản xuất + Hạn dùng (ngày) đã khai báo ở factory_batch_boxes.han_su_dung_ngay
-- (Xưởng Ba Phi) — chỉ có giá trị với lô/sản phẩm đi qua Xưởng Ba Phi, các
-- loại hàng khác (qua NCC ngoài) sẽ là NULL, trace.html tự ẩn dòng đó.
--
-- Đồng thời: thêm shipping_etd (shipments.etd) vào cả 2 view — trace.html
-- dùng làm mốc "Ngày xuất hàng" mới trong Hành trình vận chuyển.
--
-- Cách dùng: Supabase Dashboard → SQL Editor → dán toàn bộ file → Run.
-- An toàn chạy nhiều lần.

-- Cột này có trong schema.sql (dùng cho ô "ETD" ở tab Logistics) nhưng có
-- vẻ DB thật đang thiếu (lỗi "column sh.etd does not exist" khi chạy view
-- bên dưới) — thêm lại cho chắc, an toàn nếu đã có sẵn.
alter table public.shipments add column if not exists etd date;

create table if not exists public.batch_trace_products (
  id bigint generated by default as identity primary key,
  batch text not null,
  san_pham text not null,
  san_pham_en text,
  variety text,
  variety_en text,
  total_thung numeric,          -- tổng số thùng đã đóng gói của đúng sản phẩm này, tự tính khi bấm "Lấy từ hệ thống"
  public_trace_code text unique,
  trace_enabled boolean not null default false,
  created_at timestamptz default now(),
  deleted_at timestamptz
);
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'batch_trace_products'
      and constraint_name = 'batch_trace_products_batch_sanpham_key'
  ) then
    alter table public.batch_trace_products add constraint batch_trace_products_batch_sanpham_key unique (batch, san_pham);
  end if;
end $$;
alter table public.batch_trace_products enable row level security;

-- Cùng mô hình phân quyền với batch_info (xem supabase/2026-07-21_auth_roles.sql):
-- đọc = mọi người đã đăng nhập, ghi (thêm/sửa/xóa) = admin hoặc role qc —
-- vì QR truy xuất được quản lý cùng chỗ với batch_info trong tab Đơn hàng.
do $$
declare
  pol record;
begin
  for pol in (select policyname from pg_policies where schemaname = 'public' and tablename = 'batch_trace_products') loop
    execute format('drop policy if exists %I on public.batch_trace_products', pol.policyname);
  end loop;
  execute 'create policy "role_select" on public.batch_trace_products for select using (auth.role() = ''authenticated'')';
  execute 'create policy "role_insert" on public.batch_trace_products for insert with check (public.current_role() in (''admin'', ''qc''))';
  execute 'create policy "role_update" on public.batch_trace_products for update using (public.current_role() in (''admin'', ''qc'')) with check (public.current_role() in (''admin'', ''qc''))';
  execute 'create policy "role_delete" on public.batch_trace_products for delete using (public.current_role() in (''admin'', ''qc''))';
end $$;

-- View công khai riêng cho mã theo sản phẩm — NCC/Vùng/Ngày đóng hàng lấy
-- chung từ batch_info, QC/Vận chuyển lấy chung từ batch (không tách theo
-- sản phẩm được, xem ghi chú đầu file). QC luôn hiện "Đạt 100%" (xem dưới).
create or replace view public.batch_trace_product_public
with (security_invoker = false)
as
select
  btp.public_trace_code as trace_code,
  btp.san_pham as product_name,
  btp.san_pham_en as product_name_en,
  btp.variety,
  btp.variety_en,
  bi.trace_region as region,
  bi.trace_region_en as region_en,
  bi.trace_supplier_name as supplier_name,
  bi.trace_supplier_name_en as supplier_name_en,
  rb.harvest_date,
  bi.trace_packed_date as packed_date,
  btp.total_thung as qty_thung,
  'Đạt'::text as qc_status,
  100::numeric as qc_pass_rate,
  qc.qc_date,
  sh.stage as shipping_stage,
  sh.eta as shipping_eta,
  sh.received_date as shipping_received_date,
  bi.trace_batch_label as batch_label,
  exp.best_before,
  sh.etd as shipping_etd
from public.batch_trace_products btp
join public.batch_info bi on bi.batch = btp.batch
left join lateral (
  select min(ngay_nhap) as harvest_date
  from public.raw_batches
  where batch = btp.batch and deleted_at is null
) rb on true
left join lateral (
  select max(created_at)::date as qc_date
  from public.qc_checks
  where batch_code = btp.batch and check_type = 'Thành phẩm' and deleted_at is null
) qc on true
left join lateral (
  select stage, eta, etd, received_date
  from public.shipments
  where batch_code = btp.batch and deleted_at is null
  order by created_at desc
  limit 1
) sh on true
-- Hạn sử dụng = Ngày sản xuất + Hạn dùng (ngày) đã khai báo cho đúng dòng
-- Quy cách đóng thùng của sản phẩm này (factory_batch_boxes.han_su_dung_ngay,
-- tự tra theo shelf_life_reference khi lưu ở Xưởng sản xuất) — lấy sớm
-- nhất (FEFO) nếu sản phẩm này ra từ nhiều đợt sản xuất khác nhau trong lô.
left join lateral (
  select min(fb.production_date + (fbb.han_su_dung_ngay || ' days')::interval)::date as best_before
  from public.raw_batches rb2
  join public.factory_batches fb on fb.raw_batch_id = rb2.id
  join public.factory_batch_boxes fbb on fbb.factory_batch_id = fb.id
  where rb2.batch = btp.batch and rb2.deleted_at is null
    and fbb.san_pham = btp.san_pham
    and fb.production_date is not null and fbb.han_su_dung_ngay is not null
) exp on true
where btp.trace_enabled = true and btp.public_trace_code is not null and btp.deleted_at is null;

grant usage on schema public to anon;
grant select on public.batch_trace_product_public to anon;

-- QC trên trang công khai luôn hiện "Đạt 100%" — bất kể kết quả thật đang
-- ghi nhận trong qc_checks (kể cả "Đạt có điều kiện"/"Chờ xác nhận"). Chỉ
-- đổi 2 cột qc_status/qc_pass_rate, giữ nguyên mọi cột khác của view chung
-- cả lô (không được đổi thứ tự/xoá cột — xem ghi chú trong các file
-- 2026-08-19_trace_*.sql).
create or replace view public.batch_trace_public
with (security_invoker = false)
as
select
  bi.public_trace_code as trace_code,
  coalesce(bi.trace_product_name, bi.san_pham) as product_name,
  bi.trace_region as region,
  coalesce(bi.trace_variety, rb.variety) as variety,
  rb.harvest_date,
  bi.trace_packed_date as packed_date,
  bi.trace_packing_text as packing_text,
  'Đạt'::text as qc_status,
  100::numeric as qc_pass_rate,
  qc.qc_date,
  sh.stage as shipping_stage,
  sh.eta as shipping_eta,
  sh.received_date as shipping_received_date,
  bi.trace_supplier_name as supplier_name,
  bi.trace_product_name_en as product_name_en,
  bi.trace_region_en as region_en,
  bi.trace_supplier_name_en as supplier_name_en,
  bi.trace_packing_text_en as packing_text_en,
  bi.trace_batch_label as batch_label,
  bi.trace_variety_en as variety_en,
  bi.trace_packing_terms_en as packing_terms_en,
  exp.best_before,
  sh.etd as shipping_etd
from public.batch_info bi
left join lateral (
  select
    min(ngay_nhap) as harvest_date,
    string_agg(distinct chung_loai, ', ') filter (where chung_loai is not null and chung_loai <> '') as variety
  from public.raw_batches
  where batch = bi.batch and deleted_at is null
) rb on true
left join lateral (
  select max(created_at)::date as qc_date
  from public.qc_checks
  where batch_code = bi.batch and check_type = 'Thành phẩm' and deleted_at is null
) qc on true
left join lateral (
  select stage, eta, etd, received_date
  from public.shipments
  where batch_code = bi.batch and deleted_at is null
  order by created_at desc
  limit 1
) sh on true
-- Hạn sử dụng cho cả lô = mốc GẦN NHẤT (sớm nhất) trong mọi sản phẩm/đợt sản
-- xuất của lô này — an toàn theo hướng FEFO, không lấy trung bình hay mốc xa
-- nhất kẻo che mất sản phẩm nào đó sắp hết hạn hơn.
left join lateral (
  select min(fb.production_date + (fbb.han_su_dung_ngay || ' days')::interval)::date as best_before
  from public.raw_batches rb2
  join public.factory_batches fb on fb.raw_batch_id = rb2.id
  join public.factory_batch_boxes fbb on fbb.factory_batch_id = fb.id
  where rb2.batch = bi.batch and rb2.deleted_at is null
    and fb.production_date is not null and fbb.han_su_dung_ngay is not null
) exp on true
where bi.trace_enabled = true and bi.public_trace_code is not null;

grant select on public.batch_trace_public to anon;
