-- "Hạn sử dụng" theo sản phẩm — bảng tham chiếu dùng chung cho Xưởng Ba Phi,
-- khai báo 1 lần/sản phẩm thay vì gõ tay hạn dùng ở từng lô sản xuất.
--
-- Cách dùng: mở Supabase Dashboard → SQL Editor → dán toàn bộ file này → Run.
-- An toàn chạy nhiều lần (dùng IF NOT EXISTS).

create table if not exists public.shelf_life_reference (
  id bigint generated by default as identity primary key,
  san_pham text not null,
  han_su_dung_ngay numeric not null,
  ghi_chu text,
  created_at timestamptz default now(),
  deleted_at timestamptz
);
alter table public.shelf_life_reference enable row level security;

-- Cùng mô hình phân quyền với các bảng khác của Xưởng Ba Phi (raw_batches,
-- factory_batches, factory_finished_stock, factory_staff — xem
-- supabase/2026-07-21_auth_roles.sql): đọc = mọi người đã đăng nhập, ghi
-- (thêm/sửa/xóa) = admin hoặc role san_xuat.
do $$
declare
  pol record;
begin
  for pol in (select policyname from pg_policies where schemaname = 'public' and tablename = 'shelf_life_reference') loop
    execute format('drop policy if exists %I on public.shelf_life_reference', pol.policyname);
  end loop;
  execute 'create policy "role_select" on public.shelf_life_reference for select using (auth.role() = ''authenticated'')';
  execute 'create policy "role_insert" on public.shelf_life_reference for insert with check (public.current_role() in (''admin'', ''san_xuat''))';
  execute 'create policy "role_update" on public.shelf_life_reference for update using (public.current_role() in (''admin'', ''san_xuat'')) with check (public.current_role() in (''admin'', ''san_xuat''))';
  execute 'create policy "role_delete" on public.shelf_life_reference for delete using (public.current_role() in (''admin'', ''san_xuat''))';
end $$;
