-- Thêm phân loại "Hình thức" (Nội địa | Xuất khẩu) cho từng lô hàng — quản lý
-- tập trung ở module Đánh giá chất lượng (nơi tổng hợp lô hàng), tách bảng
-- riêng theo batch vì thuộc tính này áp dụng cho CẢ lô hàng (không phải theo
-- từng đơn NCC/từng lần kiểm QC), và các module sau (Logistics, Chứng từ,
-- Feedback KH...) sẽ dựa vào đây để phân biệt luồng xử lý khi mở rộng sau này.
--
-- Cách dùng: dán vào Supabase Dashboard -> SQL Editor -> Run (chạy 1 lần).

create table if not exists public.batch_info (
  id bigint generated by default as identity primary key,
  batch text not null,
  sale_type text,   -- 'Nội địa' | 'Xuất khẩu'
  created_at timestamptz default now()
);
alter table public.batch_info enable row level security;
drop policy if exists "Public full access" on public.batch_info;
create policy "Public full access" on public.batch_info for all using (true) with check (true);

-- 1 lô hàng chỉ có đúng 1 dòng phân loại (upsert theo batch từ giao diện).
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'batch_info'
      and constraint_name = 'batch_info_batch_key'
  ) then
    alter table public.batch_info add constraint batch_info_batch_key unique (batch);
  end if;
end $$;
