-- Vùng nguyên liệu: thêm "Ngày/Giờ hẹn giao" cho từng lượt nhập nguyên liệu
-- (để tính Tỷ lệ giao hàng đúng hẹn theo đầu mối) + bảng hồ sơ đầu mối thu
-- mua (raw_suppliers: địa chỉ/SĐT/ghi chú) — tách riêng khỏi raw_batches vì
-- đây là thông tin theo ĐẦU MỐI (ít đổi), không phải theo từng lô nhập.
--
-- Cách dùng: dán vào Supabase Dashboard -> SQL Editor -> Run (chạy 1 lần).
-- An toàn chạy nhiều lần (idempotent).

alter table public.raw_batches add column if not exists ngay_hen_giao date;
alter table public.raw_batches add column if not exists gio_hen_giao time;

create table if not exists public.raw_suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  phone text,
  note text,
  created_at timestamptz default now()
);
alter table public.raw_suppliers enable row level security;

do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'raw_suppliers'
      and constraint_name = 'raw_suppliers_name_key'
  ) then
    alter table public.raw_suppliers add constraint raw_suppliers_name_key unique (name);
  end if;
end $$;

-- Cùng ma trận quyền với raw_batches (module vung_nguyen_lieu) — xem
-- 2026-07-22_dynamic_permissions.sql để biết chi tiết can_write().
drop policy if exists "role_select" on public.raw_suppliers;
drop policy if exists "role_insert" on public.raw_suppliers;
drop policy if exists "role_update" on public.raw_suppliers;
drop policy if exists "role_delete" on public.raw_suppliers;

create policy "role_select" on public.raw_suppliers for select using (auth.role() = 'authenticated');
create policy "role_insert" on public.raw_suppliers for insert with check (public.can_write('vung_nguyen_lieu'));
create policy "role_update" on public.raw_suppliers for update using (public.can_write('vung_nguyen_lieu')) with check (public.can_write('vung_nguyen_lieu'));
create policy "role_delete" on public.raw_suppliers for delete using (public.can_write('vung_nguyen_lieu'));
