-- Thêm bảng theo dõi xuất hàng thành phẩm theo lô (Tồn kho, Xưởng Ba Phi).
-- 1 dòng/lô hàng: ngày xuất hàng + số lượng xuất; số lượng còn lại được tính
-- tự động = tổng thành phẩm (từ Sản xuất) - số lượng đã xuất.
--
-- Cách dùng: Supabase Dashboard → SQL Editor → dán toàn bộ → Run. Chạy 1 lần.

create table if not exists public.factory_finished_stock (
  id bigint generated by default as identity primary key,
  batch text not null,
  export_date date,
  exported_qty numeric,
  created_at timestamptz default now()
);
alter table public.factory_finished_stock enable row level security;
drop policy if exists "Public full access" on public.factory_finished_stock;
create policy "Public full access" on public.factory_finished_stock for all using (true) with check (true);

do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'factory_finished_stock'
      and constraint_name = 'factory_finished_stock_batch_key'
  ) then
    alter table public.factory_finished_stock add constraint factory_finished_stock_batch_key unique (batch);
  end if;
end $$;
