-- Chuỗi cung ứng XK — schema Supabase cho các module còn lại
-- (raw_batches của module "Vùng nguyên liệu" đã có sẵn, không tạo lại ở đây)
--
-- Cách dùng: mở Supabase Dashboard → SQL Editor → dán toàn bộ file này → Run.
-- An toàn chạy nhiều lần (dùng IF NOT EXISTS / INSERT ... WHERE NOT EXISTS).

-- ============ Nhà cung cấp ============
create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  type text,               -- 'Nội bộ' | 'Ngoại bộ'
  contact text,
  suggestion text,         -- đề xuất đặt hàng cho lô tiếp theo
  qc_pass_rate numeric,    -- %
  on_time_rate numeric,    -- %
  ranking text,            -- 'Tốt' | 'Cần theo dõi'
  created_at timestamptz default now()
);
alter table public.suppliers enable row level security;
drop policy if exists "Public full access" on public.suppliers;
create policy "Public full access" on public.suppliers for all using (true) with check (true);

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  batch_code text,          -- mã lô hàng, VD: 'MHR - 03.26'
  po_code text not null,    -- số ĐĐH, VD: '03.26'
  supplier_name text not null,
  category text,
  type text,
  quantity text,             -- số lượng đặt (thùng), VD: '5000 thùng'
  status text,              -- 'Chờ giao' | 'Đã giao' | 'Đã QC đạt' | 'Từ chối 1 phần'
  created_at timestamptz default now()
);
alter table public.purchase_orders enable row level security;
drop policy if exists "Public full access" on public.purchase_orders;
create policy "Public full access" on public.purchase_orders for all using (true) with check (true);

-- ============ Xưởng Ba Phi: Sản xuất ============
-- Mỗi dòng = 1 lượt chế biến cho ĐÚNG 1 đợt nhập nguyên liệu (raw_batches),
-- không còn theo lô hàng gộp nữa — vì 1 lô hàng có thể có nhiều đợt nhập từ
-- nhiều NCC, mỗi đợt xử lý/hao hụt riêng. batch_code/stage/progress_pct/
-- input_kg/output_kg/order_code/customer_name là cột cũ, không còn dùng
-- trong giao diện nhưng giữ lại để không mất dữ liệu lịch sử.
create table if not exists public.factory_batches (
  id bigint generated by default as identity primary key,
  batch_code text not null,
  stage text,               -- công đoạn hiện tại (cũ, không còn dùng)
  progress_pct integer default 0 check (progress_pct between 0 and 100),
  start_time text,
  expected_finish text,
  input_kg numeric,
  output_kg numeric,
  duration_hours numeric,
  created_at timestamptz default now()
);
alter table public.factory_batches add column if not exists order_code text;   -- mã đơn hàng (cũ, không còn dùng)
alter table public.factory_batches add column if not exists customer_name text; -- khách hàng (cũ, không còn dùng)
alter table public.factory_batches drop constraint if exists factory_batches_batch_code_key;
alter table public.factory_batches add column if not exists raw_batch_id bigint references public.raw_batches(id);
alter table public.factory_batches add column if not exists production_date date;   -- ngày sản xuất
alter table public.factory_batches add column if not exists finished_qty numeric;   -- thành phẩm (trái)
alter table public.factory_batches enable row level security;
drop policy if exists "Public full access" on public.factory_batches;
create policy "Public full access" on public.factory_batches for all using (true) with check (true);
-- Mỗi đợt nhập nguyên liệu chỉ có đúng 1 dòng theo dõi sản xuất.
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'factory_batches'
      and constraint_name = 'factory_batches_raw_batch_id_key'
  ) then
    alter table public.factory_batches add constraint factory_batches_raw_batch_id_key unique (raw_batch_id);
  end if;
end $$;

-- ============ Xưởng Ba Phi: Nhân sự ============
create table if not exists public.factory_staff (
  id bigint generated by default as identity primary key,
  full_name text not null,
  role text,                -- vai trò / tổ phụ trách
  shift text,                -- 'Ca sáng' | 'Ca chiều' | 'Ca tối' | 'Hành chính'
  status text,               -- 'Đang làm' | 'Nghỉ phép' | 'Nghỉ việc'
  note text,
  created_at timestamptz default now()
);
alter table public.factory_staff enable row level security;
drop policy if exists "Public full access" on public.factory_staff;
create policy "Public full access" on public.factory_staff for all using (true) with check (true);

-- ============ Xưởng Ba Phi: Tồn kho (cũ — không còn dùng trong giao diện,
-- giữ lại để không mất dữ liệu; đã thay bằng factory_finished_stock bên dưới,
-- tổng hợp trực tiếp từ Sản xuất theo lô hàng) ============
create table if not exists public.factory_inventory (
  id bigint generated by default as identity primary key,
  item_name text not null,
  category text,              -- 'Nguyên liệu' | 'Thành phẩm'
  quantity numeric,
  unit text,
  note text,
  created_at timestamptz default now()
);
alter table public.factory_inventory enable row level security;
drop policy if exists "Public full access" on public.factory_inventory;
create policy "Public full access" on public.factory_inventory for all using (true) with check (true);

-- ============ Xưởng Ba Phi: Tồn kho thành phẩm theo lô ============
-- 1 dòng/lô hàng — theo dõi đã xuất bao nhiêu, còn lại bao nhiêu so với tổng
-- thành phẩm (tổng hợp từ Sản xuất = sum(factory_batches.finished_qty) theo
-- từng lô hàng trong raw_batches).
create table if not exists public.factory_finished_stock (
  id bigint generated by default as identity primary key,
  batch text not null,        -- lô hàng (khớp raw_batches.batch)
  export_date date,           -- ngày xuất hàng
  exported_qty numeric,       -- số lượng đã xuất (trái)
  created_at timestamptz default now()
);
alter table public.factory_finished_stock enable row level security;
drop policy if exists "Public full access" on public.factory_finished_stock;
create policy "Public full access" on public.factory_finished_stock for all using (true) with check (true);
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'factory_finished_stock'
      and constraint_name = 'factory_finished_stock_batch_key'
  ) then
    alter table public.factory_finished_stock add constraint factory_finished_stock_batch_key unique (batch);
  end if;
end $$;

-- ============ Đánh giá chất lượng ============
create table if not exists public.qc_checks (
  id bigint generated by default as identity primary key,
  batch_code text not null,
  check_type text,          -- 'Đầu vào' | 'Thành phẩm'
  result text,               -- 'Chờ xác nhận' | 'Đạt' | 'Không đạt 1 phần' | 'Đạt có điều kiện'
  inspector text,
  note text,
  created_at timestamptz default now()
);
alter table public.qc_checks enable row level security;
drop policy if exists "Public full access" on public.qc_checks;
create policy "Public full access" on public.qc_checks for all using (true) with check (true);

-- ============ Logistics ============
create table if not exists public.shipments (
  id bigint generated by default as identity primary key,
  batch_code text not null,
  category text,             -- cũ, đã đổi thành "product" bên dưới
  stage text,                 -- 'Kho nội địa' | 'Cảng đi' | 'Trên biển' | 'Thông quan' | 'Cảng đến' | 'Giao khách hàng' | 'Khách đã nhận hàng'
  location text,
  eta date,
  is_featured boolean default false,  -- lô hiển thị ở khối hành trình phía trên
  created_at timestamptz default now()
);
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'shipments' and column_name = 'category'
  ) then
    alter table public.shipments rename column category to product;   -- sản phẩm
  end if;
end $$;
alter table public.shipments add column if not exists pi_po text;     -- số PI/PO
alter table public.shipments add column if not exists etd date;       -- ngày dự kiến khởi hành
alter table public.shipments enable row level security;
drop policy if exists "Public full access" on public.shipments;
create policy "Public full access" on public.shipments for all using (true) with check (true);

-- ============ Chứng từ ============
create table if not exists public.documents_checklist (
  id bigint generated by default as identity primary key,
  batch_code text not null,
  market text,                -- thị trường
  contract_ok boolean default false,
  co_ok boolean default false,
  quarantine_ok boolean default false,
  bill_of_lading_ok boolean default false,
  deadline date,
  created_at timestamptz default now()
);
alter table public.documents_checklist enable row level security;
drop policy if exists "Public full access" on public.documents_checklist;
create policy "Public full access" on public.documents_checklist for all using (true) with check (true);

-- ============ Feedback KH ============
create table if not exists public.feedbacks (
  id bigint generated by default as identity primary key,
  batch_code text not null,
  market text,
  rating integer check (rating between 1 and 5),
  feedback_text text,
  status text,                 -- 'Đã xử lý' | 'Chưa xử lý'
  created_at timestamptz default now()
);
alter table public.feedbacks enable row level security;
drop policy if exists "Public full access" on public.feedbacks;
create policy "Public full access" on public.feedbacks for all using (true) with check (true);

-- ============ Dữ liệu mẫu (giữ nguyên nội dung minh họa hiện tại) ============
-- Lưu ý: module Nhà cung cấp / PO chỉ dùng cho hàng thương mại (Chanh, Thanh
-- long, Chuối...). Dừa đi theo flow riêng (Vùng nguyên liệu → Xưởng dừa Ba
-- Phi → QC) nên không tạo dữ liệu mẫu Dừa ở đây.
--
-- Các bảng không có ràng buộc unique trên khóa nghiệp vụ (batch_code, po_code...)
-- vì người dùng có thể hợp lệ tạo nhiều dòng cùng khóa đó qua form (VD: 1 lô
-- có 2 lần kiểm QC). Vì vậy phần seed dưới đây dùng "insert ... where not
-- exists" (thay vì "on conflict do nothing", vốn không có tác dụng nếu không
-- có unique constraint) để chạy lại file này nhiều lần không bị nhân đôi dữ
-- liệu mẫu.

insert into public.suppliers (name, category, type, contact, suggestion, qc_pass_rate, on_time_rate, ranking)
select v.name, v.category, v.type, v.contact, v.suggestion, v.qc_pass_rate, v.on_time_rate, v.ranking
from (values
  ('HTX Chanh Long An', 'Chanh không hạt', 'Ngoại bộ', '090x xxx 456', 'Có thể đặt thêm cho lô sau', 96, 98, 'Tốt'),
  ('Nông hộ Bình Thuận', 'Thanh long', 'Ngoại bộ', '090x xxx 789', 'Theo dõi thêm trước khi đặt lô mới', 81, 76, 'Cần theo dõi')
) as v(name, category, type, contact, suggestion, qc_pass_rate, on_time_rate, ranking)
where not exists (select 1 from public.suppliers t where t.name = v.name);

insert into public.purchase_orders (batch_code, po_code, supplier_name, category, type, quantity, status)
select v.batch_code, v.po_code, v.supplier_name, v.category, v.type, v.quantity, v.status
from (values
  ('HTX - 03.26', '03.26', 'HTX Chanh Long An', 'Chanh không hạt', 'Ngoại bộ', '2500 thùng', 'Đã QC đạt'),
  ('BT - 04.26', '04.26', 'Nông hộ Bình Thuận', 'Thanh long', 'Ngoại bộ', '1800 thùng', 'Từ chối 1 phần')
) as v(batch_code, po_code, supplier_name, category, type, quantity, status)
where not exists (select 1 from public.purchase_orders t where t.po_code = v.po_code);

-- Không seed dữ liệu mẫu cho factory_batches nữa — bảng này giờ theo dõi
-- TỪNG đợt nhập nguyên liệu thật (raw_batch_id), không thể tạo dữ liệu mẫu
-- hợp lệ mà không có id thật từ raw_batches. Dữ liệu sẽ tự sinh khi người
-- dùng cập nhật thông tin sản xuất cho từng đợt nhập trên giao diện.

insert into public.factory_staff (full_name, role, shift, status, note)
select v.full_name, v.role, v.shift, v.status, v.note
from (values
  ('Trần Văn Hùng', 'Tổ gọt vỏ', 'Ca sáng', 'Đang làm', null),
  ('Lê Thị Hạnh', 'Tổ xử lý chống thâm', 'Ca sáng', 'Đang làm', null),
  ('Phạm Văn Tuấn', 'Tổ đóng gói', 'Ca chiều', 'Đang làm', null),
  ('Nguyễn Thị Mai', 'Quản lý ca', 'Hành chính', 'Nghỉ phép', 'Nghỉ phép đến 20/07')
) as v(full_name, role, shift, status, note)
where not exists (select 1 from public.factory_staff t where t.full_name = v.full_name);

insert into public.factory_inventory (item_name, category, quantity, unit, note)
select v.item_name, v.category, v.quantity, v.unit, v.note
from (values
  ('Dừa thô chờ gọt vỏ', 'Nguyên liệu', 850, 'kg', null),
  ('Dừa xử lý chống thâm dở dang', 'Nguyên liệu', 320, 'kg', null),
  ('Dừa thành phẩm chờ đóng container', 'Thành phẩm', 1200, 'kg', null),
  ('Dừa thành phẩm lô DUA-0714', 'Thành phẩm', 480, 'kg', 'Đã nhập kho lạnh')
) as v(item_name, category, quantity, unit, note)
where not exists (select 1 from public.factory_inventory t where t.item_name = v.item_name);

insert into public.qc_checks (batch_code, check_type, result, inspector, note)
select v.batch_code, v.check_type, v.result, v.inspector, v.note
from (values
  ('NL-0715', 'Đầu vào', 'Chờ xác nhận', 'Hạnh', 'Đang đo Brix'),
  ('DUA-0715A', 'Thành phẩm', 'Đạt', 'Tuấn', 'Không nứt, đúng size'),
  ('NL-0713', 'Đầu vào', 'Không đạt 1 phần', 'Hạnh', 'Dừa quá già'),
  ('CHANH-0712', 'Thành phẩm', 'Đạt', 'Minh', 'Đúng size, không sâu'),
  ('TL-0708', 'Thành phẩm', 'Đạt có điều kiện', 'Minh', 'Một số trái hơi mềm')
) as v(batch_code, check_type, result, inspector, note)
where not exists (
  select 1 from public.qc_checks t
  where t.batch_code = v.batch_code and t.check_type = v.check_type
);

insert into public.shipments (batch_code, pi_po, product, stage, location, etd, eta, is_featured)
select v.batch_code, v.pi_po, v.product, v.stage, v.location, v.etd, v.eta, v.is_featured
from (values
  ('DUA-0715', 'PI-0715', 'Dừa', 'Trên biển', 'Ngoài khơi Đài Loan', '2026-07-10'::date, '2026-07-22'::date, true),
  ('CHANH-0712', 'PO-0712', 'Chanh', 'Thông quan', 'Cảng Cát Lái', '2026-07-08'::date, '2026-07-18'::date, false),
  ('TL-0708', 'PO-0708', 'Thanh long', 'Trên biển', 'Biển Đông', '2026-07-06'::date, '2026-07-20'::date, false),
  ('DUA-0708', 'PI-0708', 'Dừa', 'Kho nội địa', 'Kho lạnh Bến Tre', null::date, '2026-07-25'::date, false)
) as v(batch_code, pi_po, product, stage, location, etd, eta, is_featured)
where not exists (select 1 from public.shipments t where t.batch_code = v.batch_code);

insert into public.documents_checklist (batch_code, market, contract_ok, co_ok, quarantine_ok, bill_of_lading_ok, deadline)
select v.batch_code, v.market, v.contract_ok, v.co_ok, v.quarantine_ok, v.bill_of_lading_ok, v.deadline
from (values
  ('DUA-0715', 'Nhật Bản', true, true, false, true, '2026-07-19'::date),
  ('CHANH-0712', 'Hàn Quốc', true, false, true, true, '2026-07-17'::date),
  ('TL-0701', null, true, true, true, true, null::date),
  ('DUA-0714', 'EU', true, true, true, false, '2026-07-16'::date)
) as v(batch_code, market, contract_ok, co_ok, quarantine_ok, bill_of_lading_ok, deadline)
where not exists (select 1 from public.documents_checklist t where t.batch_code = v.batch_code);

insert into public.feedbacks (batch_code, market, rating, feedback_text, status)
select v.batch_code, v.market, v.rating, v.feedback_text, v.status
from (values
  ('DUA-0714', 'Nhật Bản', 3, 'Vỏ hơi thâm khi tới nơi, có thể do thời gian nhập kho lạnh sau đóng gói bị chậm.', 'Chưa xử lý'),
  ('CHANH-0709', 'Hàn Quốc', 5, 'Đúng size, trái tươi, đóng gói chắc chắn.', 'Đã xử lý'),
  ('TL-0701', 'EU', 4, 'Giao đúng hẹn, chất lượng ổn định so với lô trước.', 'Đã xử lý'),
  ('TL-0698', 'EU', 2, 'Một số trái bị mềm, nghi do nhiệt độ kho lạnh dao động giữa hành trình.', 'Chưa xử lý')
) as v(batch_code, market, rating, feedback_text, status)
where not exists (select 1 from public.feedbacks t where t.batch_code = v.batch_code);
